language: node_js
node_js:
  # LTS version
  - "8.0"
cache:
  directories:
    - node_modules

# command to run tests
script:
  - npm test -- -u --coverage
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$COVERALL_TOKEN npm run coveralls
